#!/usr/bin/env bash
# PostToolUse hook: append edit events to docs/EDIT_LOG.md
# - Triggered by Claude Code after Edit/Write/MultiEdit completes.
# - Robust: NEVER blocks tool execution. Always exits 0 even on internal failure.
# - Append-only. Does not modify existing log lines.
set +e

INPUT="$(cat)"

# --- 1. Extract JSON fields (python3 instead of jq, for portability) ------
extract() {
  python3 - "$1" <<PY 2>/dev/null
import json, sys
data_raw = """$INPUT"""
try:
    data = json.loads(data_raw)
except Exception:
    print("")
    sys.exit(0)
key = sys.argv[1]
cur = data
for k in key.split('.'):
    if isinstance(cur, dict) and k in cur:
        cur = cur[k]
    else:
        cur = ''
        break
print(cur if isinstance(cur, str) else json.dumps(cur))
PY
}

TOOL_NAME=$(extract tool_name)
FILE_PATH=$(extract tool_input.file_path)
CWD=$(extract cwd)

# --- 2. Filter on tool name ------------------------------------------------
case "$TOOL_NAME" in
  Edit|Write|MultiEdit) ;;
  *) exit 0 ;;
esac

# --- 3. Project guard: only act inside instagram-lab -----------------------
# Walk up from CWD to find a directory literally named "instagram-lab".
PROJECT_ROOT=""
DIR="$CWD"
[ -z "$DIR" ] && DIR="$(pwd)"
while [ -n "$DIR" ] && [ "$DIR" != "/" ]; do
  if [ "$(basename "$DIR")" = "instagram-lab" ]; then
    PROJECT_ROOT="$DIR"
    break
  fi
  DIR="$(dirname "$DIR")"
done

# Fallback: detect via file_path if cwd didn't help
if [ -z "$PROJECT_ROOT" ] && [ -n "$FILE_PATH" ]; then
  DIR="$(dirname "$FILE_PATH")"
  while [ -n "$DIR" ] && [ "$DIR" != "/" ]; do
    if [ "$(basename "$DIR")" = "instagram-lab" ]; then
      PROJECT_ROOT="$DIR"
      break
    fi
    DIR="$(dirname "$DIR")"
  done
fi

[ -z "$PROJECT_ROOT" ] && exit 0

# --- 4. Compute path relative to project root ------------------------------
REL_PATH="${FILE_PATH#$PROJECT_ROOT/}"
[ "$REL_PATH" = "$FILE_PATH" ] && REL_PATH="$FILE_PATH"

# --- 5. Latest user prompt summary (best-effort) ---------------------------
CONTEXT=""
TRANSCRIPT_DIR="$HOME/.claude/projects"
if [ -d "$TRANSCRIPT_DIR" ]; then
  LATEST_JSONL=$(ls -t "$TRANSCRIPT_DIR"/*/*.jsonl 2>/dev/null | head -1)
  if [ -n "$LATEST_JSONL" ]; then
    CONTEXT=$(python3 - "$LATEST_JSONL" <<'PY' 2>/dev/null
import json, sys
path = sys.argv[1]
last_user = ""
try:
    with open(path) as f:
        for line in f:
            try:
                ev = json.loads(line)
            except Exception:
                continue
            if ev.get("type") == "user":
                msg = ev.get("message", {})
                content = msg.get("content", "")
                if isinstance(content, list):
                    for c in content:
                        if isinstance(c, dict) and c.get("type") == "text":
                            last_user = c.get("text", "")
                elif isinstance(content, str):
                    last_user = content
    first_line = last_user.splitlines()[0] if last_user else ""
    print(first_line[:80])
except Exception:
    print("")
PY
)
  fi
fi

# --- 6. Append (atomic, append-only) ---------------------------------------
LOG_DIR="$PROJECT_ROOT/docs"
LOG_FILE="$LOG_DIR/EDIT_LOG.md"
mkdir -p "$LOG_DIR"

if [ ! -f "$LOG_FILE" ]; then
  {
    echo "# Edit Log"
    echo ""
    echo "Auto-generated by .claude PostToolUse hook (scripts/log-edit.sh)."
    echo "Append-only. Do not edit manually."
    echo ""
  } >> "$LOG_FILE"
fi

TS=$(date '+%Y-%m-%d %H:%M:%S')
LINE="- [$TS] $TOOL_NAME \`$REL_PATH\`"
[ -n "$CONTEXT" ] && LINE="$LINE — $CONTEXT"

echo "$LINE" >> "$LOG_FILE"

exit 0
